### ISSUE TITLE
Add switch for soil evaporation

### ISSUE THREAD

**Issue by rcnijzink** [schymans/VOM#37]
Add a switch in the namelist to change the bare soil fraction in the vegetation cover, for the soil evaporation.

**Comment by rcnijzink** [comment]
See https://github.com/schymans/VOM/pull/38

**Comment by schymans** [comment]
It is not actually bare soil fraction. There is a hard-coded 0.2 factor in the soil evaporation equation that forces 20% of radiative energy to reach the ground even under a closed canopy, otherwise there would be 0 soil evaporation under a closed canopy, although we know that there is still some soil evaporation, either due to radiative transmissivity of even a closed canopy, or due to downwards longwave emission from the canopy or due to the soil's own heat storage. The current formulation can lead to excessive soil evaporation if the soil is wet but the canopy is actually not closed. Until we find a better solution, we should at least move this "fudge factor" to the namelist and document its meaning.

**Comment by rcnijzink** [comment]
This should be covered by https://github.com/schymans/VOM/pull/38, can this issue be closed?
