### ISSUE TITLE
Check for NaN and Inf

### ISSUE THREAD

**Issue by rcnijzink** [schymans/VOM#52]
The VOM produces NaNs with a zr set close to 0, but only when run locally. On the List HPC it runs without a problem. The NCP-values in sce_out.txt are also completely different for local runs.

Quickfix: set zr higher

For the longer term:
- Add checks for NaN and Inf with divisions
- Check for type-conversions
- Force values to be exactly zero below a certain threshold (ie. function tiny, smalles possible number of certain type)

**Comment by schymans** [comment]
I think the problem might be that a value becomes exactly zero, leading to a division by 0 error and NaN. It might have to do with the native precision of the infrastructure, which would be different on the cluster vs. your local computer. Need to check if model can run without a water table at all, and if so, we could create a threshold to make it disappear without creating a significant error, rather than becoming infinitely thin.

**Comment by rcnijzink** [comment]
Yes, I think that's what happens. It's however risky behaviour that you can still run the VOM in both cases and get completely different results. So we should think about some thresholds indeed.

**Comment by schymans** [comment]
Not sure, do you get different results, or just a result vs. no result? Could you also compare successful model runs on both systems? Anyway, we should catch the NaN error and see what exactly happens there. Can you use gdb on the HPC to debug the critical run?

**Comment by schymans** [comment]
Apparently, this issue has not re-occurred since, so I am closing this issue.
